name: Python Unit Tests
on:
  push:
    branches:
      - main
      - dev
      - coverage-badges
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          cd tests
          pytest -m bot
          mkdir docs
          coverage-badge -o docs/coverage.svg
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact - coverage badge
        uses: actions/upload-pages-artifact@v1
        with:
          path: tests/docs
      - name: Deploy to GitHub Pages - coverage badge
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Upload artifact - html report
        uses: actions/upload-pages-artifact@v1
        with:
          path: tests/htmlcov
      - name: Deploy to GitHub Pages - html report
        id: deployment
        uses: actions/deploy-pages@v1
